package view;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import theme.Temas;

/**
 * Painel de acesso a utilitários do sistema,
 * como páginas do governo e importação de arquivos XML.
 *
 * @author Elane
 */

public class UtilitariosPanel extends javax.swing.JPanel {

    
    public UtilitariosPanel() {
        initComponents();
        Temas.addVersao(pnlInferior);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        pnlUtil = new javax.swing.JPanel();
        lbIcoXML = new javax.swing.JLabel();
        lbIcoNFe = new javax.swing.JLabel();
        lbIcone3 = new javax.swing.JLabel();
        btnNFS = new javax.swing.JButton();
        btnSebrae = new javax.swing.JButton();
        btnXML = new javax.swing.JButton();
        pnlInferior = new javax.swing.JPanel();

        setBackground(new java.awt.Color(234, 239, 255));
        setMaximumSize(new java.awt.Dimension(734, 512));
        setPreferredSize(new java.awt.Dimension(734, 512));

        pnlSuperior.setBackground(new java.awt.Color(255, 255, 255));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("Utilitários");

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuperiorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTitulo))
        );

        pnlUtil.setBackground(new java.awt.Color(255, 255, 255));

        lbIcoXML.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcoXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_xml.png"))); // NOI18N
        lbIcoXML.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbIcoNFe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcoNFe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_nfe.png"))); // NOI18N
        lbIcoNFe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbIcone3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcone3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_portal.png"))); // NOI18N
        lbIcone3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNFS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNFS.setForeground(new java.awt.Color(3, 8, 255));
        btnNFS.setText("Portal NFS-e");
        btnNFS.setToolTipText("Clique para acessar");
        btnNFS.setBorder(null);
        btnNFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNFSActionPerformed(evt);
            }
        });

        btnSebrae.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSebrae.setForeground(new java.awt.Color(3, 8, 255));
        btnSebrae.setText("Emissor SEBRAE");
        btnSebrae.setToolTipText("Clique para acessar");
        btnSebrae.setBorder(null);
        btnSebrae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSebraeActionPerformed(evt);
            }
        });

        btnXML.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXML.setForeground(new java.awt.Color(3, 8, 255));
        btnXML.setText("Importar XML");
        btnXML.setToolTipText("Clique para acessar");
        btnXML.setBorder(null);
        btnXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUtilLayout = new javax.swing.GroupLayout(pnlUtil);
        pnlUtil.setLayout(pnlUtilLayout);
        pnlUtilLayout.setHorizontalGroup(
            pnlUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtilLayout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(pnlUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbIcone3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNFS, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSebrae)
                    .addComponent(lbIcoNFe, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbIcoXML, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXML))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        pnlUtilLayout.setVerticalGroup(
            pnlUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtilLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(pnlUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbIcone3)
                    .addComponent(lbIcoNFe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIcoXML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUtilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNFS)
                    .addComponent(btnSebrae)
                    .addComponent(btnXML))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pnlUtilLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbIcoNFe, lbIcoXML, lbIcone3});

        pnlInferior.setBackground(new java.awt.Color(5, 4, 45));
        pnlInferior.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUtil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlInferior, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pnlUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSebraeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSebraeActionPerformed
       
   String url = "https://amei.sebrae.com.br/auth/realms/externo/"
               + "protocol/openid-connect/auth?" + "client_id=emissor-nfe-frontend"
               + "&redirect_uri=https%3A%2F%2Femissornfe.sebrae.com.br%2F"
               + "&state=0ea19ffa-e099-4122-9553-f04b9a1757c8"
               + "&response_mode=fragment" + "&response_type=code"
               + "&scope=openid" + "&nonce=83338307-3569-460b-9e04-72b760b7c152";

    try {
        Desktop.getDesktop().browse(new URI(url));
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Página não encontrada.","Erro",
                JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnSebraeActionPerformed

    private void btnNFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNFSActionPerformed
        
    try {
        Desktop.getDesktop().browse(
            new URI("https://www.nfse.gov.br/EmissorNacional/Login?ReturnUrl=%2femissornacional")
        );
    } catch (IOException | URISyntaxException e) {
        JOptionPane.showMessageDialog(null, "Página não encontrada.","Erro",
            JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_btnNFSActionPerformed

    private void btnXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXMLActionPerformed
        
    JFileChooser fileChooser = new JFileChooser();

    fileChooser.setMultiSelectionEnabled(true);
    FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivos XML (*.xml)","xml");
    fileChooser.setFileFilter(filtro);

    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home"))
    );

    int resultado = fileChooser.showOpenDialog(null);

    if (resultado == JFileChooser.APPROVE_OPTION) {File[] arquivos = fileChooser.getSelectedFiles();

        if (arquivos.length == 0) {JOptionPane.showMessageDialog(null,
                "Nenhum arquivo XML foi selecionado.","Busca de XML",JOptionPane.WARNING_MESSAGE);
            
        return;
        }

        JOptionPane.showMessageDialog(null,arquivos.length + " arquivo(s) XML selecionado(s) com sucesso.",
            "Busca de XML",JOptionPane.INFORMATION_MESSAGE);

    } else {

        JOptionPane.showMessageDialog(null,"Nenhum arquivo foi selecionado.","Busca de XML",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    }//GEN-LAST:event_btnXMLActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNFS;
    private javax.swing.JButton btnSebrae;
    private javax.swing.JButton btnXML;
    private javax.swing.JLabel lbIcoNFe;
    private javax.swing.JLabel lbIcoXML;
    private javax.swing.JLabel lbIcone3;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JPanel pnlUtil;
    // End of variables declaration//GEN-END:variables
}
